### ISSUE TITLE
Mutable builder access?

### ISSUE THREAD

**Issue by polachok** [colin-kiegel/rust-derive-builder#112]
My use case is like this:
```
struct Test {
  id: u64,
  a: i32,
  b: i32
}
```
where id = hash((a, b)). I don't want to expose id as .set_id() to limit user's ability to make a mistake. It would be nice to have a method like validate() with mutable access to the builder, then I could do builder.id = ...

**Comment by fluffysquirrels** [comment]
Yes, that makes sense.

I believe you can already make a custom .build() method. You could let the
user set .a, .b, then calculate .id in your .build()? On my phone so
haven't tested this.

On 12 Mar 2018 11:36, "Alexander Polakov" <notifications@github.com> wrote:

My use case is like this:

struct Test {
  id: u64,
  a: i32,
  b: i32
}

where id = hash((a, b)). I don't want to expose id as .set_id() to limit
user's ability to make a mistake. It would be nice to have a method like
validate() with mutable access to the builder, then I could do builder.id =
...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/colin-kiegel/rust-derive-builder/issues/112>, or mute
the thread

**Comment by polachok** [comment]
Ah, thanks, looks like I missed `#[builder(build_fn(skip))]` in the docs.

**Comment by fluffysquirrels** [comment]
No problem! Let us know if that doesn't work out.

Can you close this issue for me? I don't seem to have permissions.

**Comment by polachok** [comment]
build_fn(skip) + builder(setter(skip)) works but its ergonomics is not ideal (have to manually set all fields), still better than manually writing all setters though.
