### ISSUE TITLE
Support custom Error Type of build method result rather than String?

### ISSUE THREAD

**Issue by jmjoy** [colin-kiegel/rust-derive-builder#158]
I think it is a good idea to support specifying a custom error type which implemented `From<String>` in the builder attribute.

**Comment by TedDriggs** [comment]
I think our preference here would be to have a strongly-typed error exposed by the crate as discussed in #60. If we had that, I could see us including a native `map_err` attribute so that someone could transform the error without exposing `derive_builder`'s own error type directly. If that's your goal, let's continue the discussion there.

Today, it should be possible to rename the crate-provided builder function ([source](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder/src/options/darling_opts.rs#L45)), and then add a custom `impl FooBuilder` block with `fn build(self) -> Result<Foo, MyError>`. Since we don't want to encourage parsing our error strings, I think that might be the closest we'd get to what's requested here.
