### ISSUE TITLE
Automatic documentation does not work

### ISSUE THREAD

**Issue by killercup** [colin-kiegel/rust-derive-builder#16]
From the generic test as output by `cargo expand --test generic_structs`:

```rust
#[allow(dead_code)]
impl<T> GenLorem<T> {
    /// Set `$field_name`
    ///
    /// auto-generated by [derive_builder](https://crates.io/crates/derive_builder)
    fn ipsum<VALUE: Into<String>>(mut self, value: VALUE) -> Self {
        self.ipsum = value.into();
        self
    }
    /// Set `$field_name`
    ///
    /// auto-generated by [derive_builder](https://crates.io/crates/derive_builder)
    fn dolor<VALUE: Into<T>>(mut self, value: VALUE) -> Self {
        self.dolor = value.into();
        self
    }
}
```

**Comment by killercup** [comment]
Sieht auch nicht so einfach aus. `#[doc=concat!(...)]` funktioniert auch [nicht](https://play.rust-lang.org/?code=macro_rules!%20lel%20%7B%0A%20%20%20%20(%24x%3Aident)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%23%5Bdoc%3Dconcat!(%22hello%22%2C%20%24x)%5D%0A%20%20%20%20%20%20%20%20struct%20Foo%3B%0A%20%20%20%20%7D%0A%7D%0A%0Alel!(world)%3B%0A%0Afn%20main()%20%7B%7D&version=stable&backtrace=0).

**Comment by colin-kiegel** [comment]
Ok - that was unexpected. Any suggestions other than static text?

**Comment by killercup** [comment]
One possibility is: Just copy all attributes from the fields to the setter methods. Documentation (and stuff like `#[doc(hidden)]`) should just work. Then, add another gotcha item "Only documentation attributes are supported for now".

**Comment by colin-kiegel** [comment]
Ok, the current code is just something like `#[doc="Set '$fieldname'"]` and therefore `$fieldname` is just part of a string instead of being a token. That makes sense now.

I understand your suggestion like this: We would copy doc-attributes and silently "skip" non-doc attributes. I.e. non-doc attributes just don't end up at the setter-methods, but don't break anything either. Correct?

**Comment by killercup** [comment]
At first, I would just copy all attributes. Filtering them might be tricky.

**Comment by colin-kiegel** [comment]
PS: I would still like to have a fallback to at least static auto-generated doc-comment if no user doc-comment is present.

**Comment by colin-kiegel** [comment]
Hm. Ok, I'm leaning towards prioritizing to accept all sorts of valid rust code first and _then_ add features. This is why I would start with skipping and then add filtering - instead of the other way around.

I think "just works" is more valuable than "does some tricks, but doesn't always work (if you don't do X and Y)". But this is just my current feeling.

**Comment by colin-kiegel** [comment]
I just think the impact of negative experiences (like X doesn't work) is often greater than the impact of positive experiences (can do Y).

But this is all a bit hypothetical right now, because we are not talking about explicit examples which might break. Maybe we could elaborate on that first. :-)

**Comment by colin-kiegel** [comment]
The generated doc-comment now is only static: `/// Setter-method`.

Lets continue the discussion in #13 and #14.
