### ISSUE TITLE
Add a builder pattern that uses mutable references and `take`s fields in build

### ISSUE THREAD

**Issue by jplatte** [colin-kiegel/rust-derive-builder#166]
In addition to the current patterns that this library implements, it would be nice to have one that works like the mutable, default pattern but instead of cloning all of the fields inside build, it replaces the builder's fields with `None` (using `Option::take`). To apply this to the example from the crate docs:

```rust
fn build(&mut self) -> Result<Lorem, String> {
    Ok(Lorem {
        ipsum: self.ipsum.take().ok_or("ipsum must be initialized")?,
    })
}
```

The only downside to this is that using `build()` twice in a row on a builder with at least one mandatory field will fail.

I'm not entirely sure how this would interact with all of the attributes this crate currently offers, but I'm sure it could be made to work (maybe with only a subset of attributes supported).

If deeded useful, I will take care of the implementation :)

**Comment by TedDriggs** [comment]
What's the advantage of this approach over the `owned` pattern? That one enforces the call-once semantic using the type system, which seems more idiomatic in Rust than a `build` method that panics on subsequent calls. However, I could be missing some advantage of bypassing the clone requirement using this approach compared to the existing one.

**Comment by jplatte** [comment]
This approach is the most ergonomic one IMO. It doesn't require field types to implement `Clone`, and setters can intuitively be used conditionally (without reassigning the builder).

**Comment by TedDriggs** [comment]
What happens if you make a mutable setter builder with a custom build method that consumes the builder?

**Comment by jplatte** [comment]
I'm not sure what you mean. Having a `build` method that consumes the builder doesn't make sense with this pattern as then `.build` couldn't be chained off of a setter.

**Comment by TedDriggs** [comment]
Sorry, I wasn't thinking straight in that last comment.

I get that having to assign the builder in conditional calls is frustrating, but I think having a method that consumes the struct lie about doing so is not idiomatic Rust, and that `derive-builder` shouldn't provide functionality that encourages such behavior.

It's possible to implement this today with the crate by skipping the build function in favor of implementing a custom one. That's the best path forward here, since that also allows the caller to provide a doc comment that explains the non-idiomatic behavior.
