### ISSUE TITLE
Create Builder from instance ( to_builder() )

### ISSUE THREAD

**Issue by mseravalli** [colin-kiegel/rust-derive-builder#170]
Add the possibility of creating a builder from an instance with `to_builder()` so that we can create new instances from an existing one.

```rust
#[derive(Builder)]
struct Lorem {
    ipsum: i32,
    dolor: i32,
}

fn do_smth() ... {
    ...
    let lorem = LoremBuilder::default().ipsum(42).dolor(0).build()?;
    let more_dolor = lorem.to_builder().dolor(1).build()?;
    ...
}
```

**Comment by TedDriggs** [comment]
This is something I frequently add to my own structs, but I usually just do it with my own `impl` block since the code required is pretty short:

```rust
pub fn builder() -> LoremBuilder {
    LoremBuilder::default()
}
```

We did previously agree that we'd add it as `builder` if we added the inherent method for the caller.

# Points For
1. It's a very common ergonomic choice for calling crate offers to provide this.

# Points Against
1. If the crate auto-generates this, it will be in its own `impl` block. That shows up in the generated documentation, which some people don't like.
2. This code basically never changes: Unlike many of the builder internals, this stays the same when the fields of the builder change. That makes the time savings and correctness wins of the code generation smaller.

If we do add it, it'll need to be opt-in. What would you call in the `#[builder(...)]` attribute?

**Comment by mseravalli** [comment]
Thanks for the fast answer, but, if I understand it correctly, the proposed solution does not copy the current existing values of the instance, right?
I was thinking about a solution for easily duplicating an instance and maybe overwrite a single attribute. Something like

```rust
struct Lorem {
    ipsum: i32,
    dolor: i32,
}

pub fn builder(&self) -> LoremBuilder {
    LoremBuilder::default().ipsum(self.ipsum).dolor(self.dolor)
}
```

This would be helpful in structs with many attributes. Additionally, it would allow to use immutable structs and whenever we need to perform a change we create a new one. Yes, it might not be the perfect approach, but in some contexts it might make sense.

**Comment by TedDriggs** [comment]
Ah, I misunderstood. I think the more idiomatic way to express that in Rust would be `impl From<Lorem> for LoremBuilder { ... }`, but I've never seen that in any other crate's builders - or in the builders exposed by the standard library. Can you point to some examples of this in other Rust code please?

**Comment by mseravalli** [comment]
Sorry for the late reply, I don't have specific examples in other Rust code. I was trying to create new immutable objects from existing ones and I am missing a way to do it (maybe it is already possible, but I don't know how).
I have more of a Java background and when dealing with immutable objects methods like [`toBuilder()`](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Message.html#toBuilder--) and [`mergeFrom(...)`](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Message.Builder.html#mergeFrom-com.google.protobuf.Message-) are really helpful when creating new objects from existing ones.
I think this functionality is currently missing in rust.

**Comment by TedDriggs** [comment]
No worries.

For now, I'd suggest a hand implementation that takes this form:

```rust
impl From<Foo> for FooBuilder {
    fn from(other: Foo) -> Self {
        FooBuilder::default().first_field(other.first_field).build().unwrap()
    }
}
```

This will allow you to write `FooBuilder::from(my_instance)` or `let builder: FooBuilder = my_instance.into();` and is the idiomatic way of writing conversions in Rust.

If we get more requests for generating that conversion in this crate we can revisit, but since this is the first time it's come up I don't think it's justified for inclusion in the macro.

**Comment by mseravalli** [comment]
Thanks for the reply!

**Comment by jonas-x** [comment]
Hi! I'd like to add a +1 on this feature request. I, too, come from a Java background and absolutely love libraries with this capability. 

For now I can implement `From` myself where needed in my project. But my fear is that over time, if fields are added, I'll forget to update the from trait impl.

I can give it at try to add this to the derive macro if you'd like?
