### ISSUE TITLE
Lifetime support?

### ISSUE THREAD

**Issue by mre** [colin-kiegel/rust-derive-builder#21]
Just tried using rust-derive-builder for a struct with lifetimes:

``` rust
#[macro_use] extern crate custom_derive;
#[macro_use] extern crate derive_builder;

custom_derive! {
    #[derive(Default, Builder)]
    struct Channel<'a> {
        token: &'a str,
        special_info: i32,
        // .. a whole bunch of other fields ..
    }
}

impl Channel {
    // All that's left to do for you is writing a method,
    // which actually *does* something. :-)
    pub fn build(&self) -> String {
        format!("The meaning of life is {}.", self.special_info)
    }
}

fn main() {
    // builder pattern, go, go, go!...
    let x = Channel::default().special_info(42u8).build();
    println!("{:?}", x);
}
```

I get the following error:

``` rust
6:22 error: expected ident, found 'a
src/main.rs:6     struct Channel<'a> {
                                 ^~
error: Could not compile `derive-test`.
```

Can lifetimes be easily added? If not, are there any workarounds?

**Comment by colin-kiegel** [comment]
Thanks for your feedback. I'll look into it when I find some spare time.
As a quick workaround you might use `String` and just copy the data for now.

**Comment by killercup** [comment]
Colin, I remember there were some issues with matching lifetimes in macros
(I think there is an RFC to add lifetime token types), _but_ in this case
can we just match on `<$generics:tt>` and copy the whole thing?


Colin Kiegel <notifications@github.com> schrieb am Mo. 15. Aug. 2016 um
09:39:

**Comment by colin-kiegel** [comment]
Yeah, I remember the same thing, i.e. we can't match specifically on
lifetimes right now. Your suggestion is probably the only way to do it
right now. I am confident this will work, because when we match on fields
types later on, the lifetime there should just be part of the matched type.

**Comment by colin-kiegel** [comment]
Hm, looks like I was to quick on this. I was sure I tested this on stable and beta, too - but travis proves me wrong... So this is working on nightly, but not on beta + stable yet.

https://travis-ci.org/colin-kiegel/rust-derive-builder/jobs/152447585#L253

Rust expects an identifier when expanding a generic struct, and we can't coerce a lifetime into an identifier. Too bad.

This looks like a bug which has been fixed in rustc 1.12, i.e. we have to wait for 2 releases. I'll revert the change and rebase my pull request (again) later.

@killercup: SORRY about the little mess ^^

**Comment by colin-kiegel** [comment]
@mre: You are lucky - there is a workaround with derive_builder v0.1.0 and stable rust and it is not too bad actually. Just use a generic struct `struct Channel<T>` and substitute `&'a YourType` as `T` when you instantiate it. It's a bit longer than `'a` but that is the only disadvantage I can see. :-)

A full example looks like this

```rust
#[macro_use] extern crate custom_derive;
#[macro_use] extern crate derive_builder;

custom_derive! {
    #[derive(Debug, Builder)]
    struct Channel<T> {
        token: T,
        special_info: i32,
        // .. a whole bunch of other fields ..
    }
}

impl<T> Channel<T> {
    pub fn new<X: Into<T>>(token: X) -> Self {
        Channel {
            token: token.into(),
            special_info: 0,
        }
    }
}

impl<T: ::std::fmt::Display> Channel<T> {
    // All that's left to do for you is writing a method,
    // which actually *does* something. :-)
    pub fn build(&self) -> String {
        format!("{}. The meaning of life is {}.", self.token, self.special_info)
    }
}

fn main() {
    let ch: Channel<&'static str> = Channel::new("Hello world!");
    let x: String  = ch.special_info(42u8).build();
    println!("{:?}", x);
}
```

**Comment by mre** [comment]
@colin-kiegel thanks for that! I will try it out as soon as I get a chance.
Just out of curiosity: Does it support multiple lifetimes? I don't have a use-case for that right now, just want to learn a bit more.

**Comment by colin-kiegel** [comment]
@mre: Yes, the workaround supports multiple lifetimes, because the lifetime is hidden in a type parameter: You can both
* use as many different type parameters as you want,
* hide as many lifetimes within each type parameter as you want.

However, you can only access methods of your generic type, if they are defined in a trait and if you add the appropriate trait boundary (e.g. the boundary `T: ::std::fmt::Display` is neccessary to call `Display::fmt()` on `T` - implicit in the `format!` macro).

**Comment by mre** [comment]
Nice to know. Thanks for your work. :relaxed:

**Comment by colin-kiegel** [comment]
reopening .. github didn't get the meaning of '_revert_ fix #21' ^^

Btw. the fix currently works on nightly and beta (=rustc 1.12). I.e. with the next stable release we should be able to roll it out. :-)

**Comment by nbigaouette** [comment]
What's the status on this? Can fda318a9adc447396af31378d89800f13a2296cd be used with rust 1.13?

**Comment by colin-kiegel** [comment]
v0.3.0 released
