### ISSUE TITLE
Validation of default fields

### ISSUE THREAD

**Issue by r-arias** [colin-kiegel/rust-derive-builder#251]
Hi!

I stumbled across an issue where `derive_builder` is working as *documented*, but not necessarily as *expected*.

I am using [`vaultrs`](https://github.com/jmgilman/vaultrs/issues) which uses `derive_builder`, e.g. for its [VaultClientSettings](https://docs.rs/vaultrs/0.6.0/vaultrs/client/struct.VaultClientSettings.html).

I'll describe an issue I stumbled upon; let me say up front that I am not sure it is actually a problem in `derive_builder`. But, it may be that the documentation could be improved.

[`vaultrs`](https://github.com/jmgilman/vaultrs/issues) uses `derive_builder` for its [VaultClientSettings](https://docs.rs/vaultrs/0.5.4/vaultrs/client/struct.VaultClientSettings.html)

The code looks like this:

```rust
/// Contains settings for configuring a [VaultClient].
///
/// Most settings that are not directly configured will have their default value
/// pulled from their respective environment variables. Specifically:
///
/// * `address`: VAULT_ADDR
/// * `ca_certs: VAULT_CACERT / VAULT_CAPATH
/// * `token`: VAULT_TOKEN
/// * verify`: VAULT_SKIP_VERIFY
///
/// The `address` is validated when the settings are built and will throw an
/// error if the format is invalid.
#[derive(Builder, Clone, Debug)]
#[builder(build_fn(validate = "Self::validate"))]
pub struct VaultClientSettings {
    #[builder(setter(into), default = "self.default_address()")]
    pub address: String,
    #[builder(default = "self.default_ca_certs()")]
    pub ca_certs: Vec<String>,
    #[builder(setter(into), default = "self.default_token()")]
    pub token: String,
    #[builder(default = "self.default_verify()")]
    pub verify: bool,
    #[builder(setter(into, strip_option), default = "1")]
    pub version: u8,
    #[builder(default = "false")]
    pub wrapping: bool,
}
```

Now, the comment shows a misunderstanding of how `derive_builder` works. The [docs](https://docs.rs/derive_builder/latest/derive_builder/#pre-build-validation) say:
> Default values are applied after validation, and will therefore not be validated!

In this particular case, if one builds their `VaultClientSettings` in a specific way, the validate function panics, because it assumes it's validating an initialized builder object, but defaults are not applied yet.

Now, I am aware that `derive_builder` is working as documented and that it's simple to change the `vaultrs` implementation to more gracefully handle this. I created an [issue](https://github.com/jmgilman/vaultrs/issues/29) (and a [PR](https://github.com/jmgilman/vaultrs/pull/30)), there, as well.

My question is: is there a particular reason validation takes place *before* applying defaults or is it just implemented that way? From the perspective of someone using the library, I think I'd want the validation to validate a struct I'm actually creating and not a kind of intermediate state **after** adding "manual" builder parameters and **before** applying defaults.

**Comment by TedDriggs** [comment]
Validation takes place before defaulting for a couple reasons:

1. Populating defaults takes work - we may have to create a whole instance of the deriving type, for example. We wanted validation to be "zero-cost" in terms of performance, so that creation would have been tough to accept.
2. Defaulting does not write its values into the builder struct fields, so there's no good way to expose those defaulted values to the validation function. Indeed, defaulting and target struct construction are intertwined, so there's no moment where one could observe defaulted values before the target is constructed.

Personally, I'd suggest that `vaultrs` use a tighter type for `address`, so that there's not a need to do validation on it at build time. If there's no good existing type, a custom type with `TryFrom<&str>` and `FromStr` impls would work well. In that situation, the default would also need to be changed to `default = "self.default_address()?"` to reflect the possibility of unsuitable data coming in from the environment variable.

**Comment by r-arias** [comment]
Hey Ted,
thanks for the answer. That reasoning makes sense.

Thanks for the suggestion regarding the type change in `vaultrs`, seems like a good idea. I'll pass it along. :slightly_smiling_face: 

Cheers,
R
