### ISSUE TITLE
Combination of #[builder(default = "foo", field(...)] should error out

### ISSUE THREAD

**Issue by Xion** [colin-kiegel/rust-derive-builder#269]
Right now, the `default` value is silently ignored.

This is only indirectly hinted at in the docs where it says that a type `T` in `field(type="T")` needs to implement `Default`. It is not stated that the provided custom `default` would be ignored, however.

**Comment by TedDriggs** [comment]
Is it ignored by the `build` method? I'm a bit surprised by that.

According to [the code](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder_core/src/macro_options/darling_opts.rs#L336-L362), we have a check already that will  complain if `field(build = "...")` is used in conjunction with `default`. However, I would expect that it's fine to change a field's type in the builder using the `#[builder(field(type = "..."))]` and still have the `default` apply at the right time in `build_fn`.

The reason that `T` needs to `impl Default` is because we need to create it "empty" when we start the builder. By default, we use `Option` wrappers around all fields and that's sufficient to guarantee we can give those fields default values at builder creation. We don't use the body of the `#[builder(default = "...")]` expression until we're in the `build` method, since we don't want to do potentially-expensive initialization that won't be needed.

**Comment by TedDriggs** [comment]
Thanks for that!

It looks like the issue is [here](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder_core/src/macro_options/darling_opts.rs#L842), where the presence of a custom type will push us to use the `Move` strategy, which would preclude the optionality check.

@ijackson do you remember if there’s a reason we didn’t initially check for this?
