### ISSUE TITLE
Generated Builder documentation snippet fails doc-test

### ISSUE THREAD

**Issue by azriel91** [colin-kiegel/rust-derive-builder#46]
For the following struct:

```rust
#[macro_use]
extern crate derive_builder;

#[derive(Builder)]
struct Foo { a: i32 }
```

and the current `master` (`32a6437`), `cargo test` fails the doc test because `FooBuilder` and `Foo` are not imported:

```
failures:

---- src/lib.rs - FooBuilder (line 8) stdout ----
	error[E0412]: cannot find type `FooBuilder` in this scope
 --> <anon>:2:16
  |
2 | let builder = <FooBuilder as Default>::default();
  |                ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `Foo` in this scope
 --> <anon>:4:16
  |
4 | let _x: Result<Foo, String> = builder.build();
  |                ^^^ not found in this scope

error: aborting due to previous error(s)
```

I tried updating the builder doc template like so:

````markdown
Builder for `{struct_name}`.

# Examples

```rust
# use {qualified_module_name}::{{{struct_name}, {builder_name}}};

let builder = <{builder_name} as Default>::default();
// .. call some setters on `builder`
let _x: Result<{struct_name}, String> = builder.build();
```
````

but I haven't figured out how to get the module name from the `TokenTree` or confirmed if it's possible / impossible.

---

Side note: I picked up master because I wanted the `#![deny(missing_docs)]` fix

**Comment by colin-kiegel** [comment]
thanks - that's going to get difficult I guess..

I can't see a way to get the module path from the stringified TokenTree. Even if we could, the crate might use the facade pattern to re-export `FooBuilder` with a different path, e.g. something like
```rust
#[macro_use]
extern crate derive_builder;

pub use internal::FooBuilder; // <-- re-export with different public path
mod internal { // private module
    #[derive(Builder)]
    pub struct Foo { a: i32 }
}
```

So even if we could get the module path, this re-exportation will be a headache, since it is non-local and the current derive-API only gives us local information.

Right now I see only see these two options:
- Remove the example from the generated documentation
- Add an option to tell derive-builder the public path and re-introduce the example conditionally

---
PS: There is the [module_path!()](https://doc.rust-lang.org/std/macro.module_path.html) macro. So we do have limited access to this information - but only after code generation and only in certain positions. It will not be possible to use that macro as part of a path or in documentation in general (with respect to the surrounding module). That does not seem to be of any help here.

**Comment by azriel91** [comment]
We could always do `rust,ignore` for the code snippet 😅

**Comment by colin-kiegel** [comment]
true - but the doc-test fails because the documentation is _incorrect_ - so I would rather fix the documentation, or we will get complaints about incorrect documentation. :-)
