### ISSUE TITLE
Getters

### ISSUE THREAD

**Issue by killercup** [colin-kiegel/rust-derive-builder#7]
I wrote in https://github.com/colin-kiegel/rust-derive-builder/pull/4#issuecomment-238043177:

> I really want this to generate idiomatic Rust, so getters names would be prefixed with `get_`, e.g. `get_foo()` and `get_foo_bar()`.
> 
> If I read https://github.com/rust-lang/rust/issues/29599 correctly, it's not possible to generate `ident` on stable. If we were to do getters on nightly only, [interpolate_idents](https://github.com/SkylerLipthay/interpolate_idents) might be helpful ([usage example](https://github.com/aidanhs/ayzim/blob/713497c264/src/cashew.rs#L162-L178)).
> 
> A more creative solution for stable might be creating a single `get(&self) -> new_sub_module::Getter` method, where `Getter` is a newtype that implements methods to get each of the struct fields, so you can do `x.get().foo()`.

**Comment by nielsle** [comment]
It would be great to have a solutiom that allowed the user to use the builder as something like a rust-typemap. (Yes I know it is out of scope, but it would be great to have :-) ). I tried to propose something similar over here

https://github.com/DanielKeep/rust-custom-derive/issues/19

**Comment by colin-kiegel** [comment]
@nielsle thx for your suggestion. But I don't see that in this crate, because it's a different use case with different requirements.

But feel free to create a fork of derive_builder and replace https://github.com/colin-kiegel/rust-derive-builder/blob/master/src/derive_builder.rs#L47 and https://github.com/colin-kiegel/rust-derive-builder/blob/master/src/derive_builder.rs#L80

**Comment by colin-kiegel** [comment]
as long as we can't make this idiomatic, I would rate a workaround with low priority. It is already possible to make the fields public, which seems good enough as a workaround.

**Comment by colin-kiegel** [comment]
If a field is unset but has a default value, should the getter return `None` or the default value?

**Comment by TedDriggs** [comment]
@colin-kiegel I was thinking about that as part of the work on #85. As shown in the sample code in #79, I'd like to expose at least private getters with the signature `get_foo(&self) -> Result<T, String>`, which returns the explicit value of `foo`, the default value of `foo`(which may require invoking the `default` at the struct level), or an uninitialized field error. These private getters would make writing a validator function and/or custom build function much cleaner.

The downside seems to be that they require doing one of the following:

1. Take `&mut self` so that they can cache the default value after computing it once. Using them in conjunction with the validator hook would mean the validator had to take `&mut self`, and that would require changing the signature of the `build` method.
1. Cache the default value, but use a `Cell` to avoid calling the default methods more than once. This field would have to be private, which is a breaking change if anyone is depending on struct update syntax without a trailing `..` clause.
1. Eagerly compute default values in `FooBuilder::default()` and prepopulate the fields with the values. This would interfere with any attempt at a set-once model.

**Comment by colin-kiegel** [comment]
What about this use case, where someone wants to query the builder whether a field is already set? If we don't include computing the default value, then we could allow this via `get_foo(&self) -> Option<T>`. It seems like we can't have both.

If we decide to include computing custom defaults, we could also

0.  Accept that calling `get_foo(&self)` can be expensive, when custom defaults are defined.

**Comment by TedDriggs** [comment]
The "is set" case can be checked by querying the field directly, especially if the author is writing a custom `build` function or a validator.

**Comment by colin-kiegel** [comment]
Ok, I was thinking about the three-crate-scenario (i) derive_builder, (ii) author of builder, (iii) user of builder. I'm wondering if there could be a use case where the user of the builder wants to inspect the input already given to the builder. You're saying this would only be possible if the _author_ of the builder already made the fields public (which is probably an un-idiomatic choice as discussed in #86).

Maybe such a use case is unlikely. I can only imagine a cases where the user of the builder uses dynamic input and either (a) wants to conditionally apply a default value which is different from the stock default, but the setters have once-only-semantics or (b) wants to display the given inputs somehow, like "please review your `PizzaOrder` then confirm". Both cases don't seem like day-to-day use-cases.

**Comment by colin-kiegel** [comment]
Another possible problem I can imagine is this.

I would very much like `#[builder(default)]` to be a non-breaking addition. That is, again in the three crate-scenario, if the author of the builder adds `#[builder(default)]` to a previously undefaulted field, it should not break any previously working code for the user of the builder.  This would imply that we can't change signatures when `#[builder(default)]` is added to a field.

Getters would have to return `Result` even if their only failure mode would be `None`. Could this be awkward or annoying for users of the builder?

And is it really safe to say that users of the builder should not depend on getters to fail in a specific situation (like no value was supplied)? Because otherwise adding `#[builder(default)]` to a field _would_ be a breaking change.

**Comment by TedDriggs** [comment]
This issue hasn't had any movement in ~5 years, so I'm concluding that this doesn't come up much in practice and am closing the issue.
