### ISSUE TITLE
Allow author to opt out of public builder fields

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#86]
It is considered a breaking change in Rust to add a field to a struct whose fields were all public in a previous release, as the added field can break pattern matches and struct literals. Many builder use cases do not require access to the partially-initialized fields, so exposing them increases the author's risk of a breaking change for no discernible use-case.

# Proposal
Add a new option at the struct level: `#[builder(fields(...))]`. This option takes **either:**

* `public` - for back-compat reasons, this probably needs to be the default. (I view this as unfortunate, since I think users should have to opt into broadening the API surface they expose)
* `private`

This option will not be valid at the individual field level.

**Comment by colin-kiegel** [comment]
Note: As discussed in PR https://github.com/colin-kiegel/rust-derive-builder/pull/87#pullrequestreview-33939080, we will change the default visibility of builder fields from public to private. Because private fields seem a more idiomatic default. But we will _not_ do it immediately, in order to give users time to adapt. An intermediate release will issue deprecation warnings.

**Comment by colin-kiegel** [comment]
released with v0.4.5 - thanks @TedDriggs :-)
